name: "Request for files"
description: "Create a report to help us improve"
title: "Files: "
labels: ["files request"]
body:
  - type: input
    attributes:
      label: Problem description
      description: |
        Which files do you add?
    validations:
      required: true

